spring:
  application:
    name: customer  # correspond à customer-dev.yml dans le repo Git

  profiles:
    active: dev  # profil actif

  config:
    import: "configserver:"  # <-- syntaxe correcte ici

  cloud:
    config:
      uri: http://localhost:8888  # l’URL de ton Config Server
      fail-fast: true
