server:
  port: 8888

spring:
  application:
    name: confServer  # Remplacez par le nom de votre application

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ton-utilisateur/ton-depot.git  # Remplacez par l'URL de ton dépôt GitHub
          searchPaths: configFiles  # Le dossier contenant les fichiers de configuration dans le dépôt
          cloneOnStart: true  # Cela permet de cloner le dépôt à chaque démarrage du serveur de configuration
          username:   # Si nécessaire, ajoute tes informations d'authentification
          password:
