server:
  port: 8888

spring:
  application:
    name: confServer

  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanaaazza/MicrosserviceTP1
          searchPaths: configFiles
          default-label: main  # branche à utiliser
          cloneOnStart: true
